export const UNLOCK = '$X';
export const HOME = '$H';
export const STATUS = '?';
export const RESET = '\x18';
export const HOLD = '!';
export const RESUME = '~';
export const RUN = '$SD/Run=/';
export const JOG = '$J=';
export const WAIT_FOR_JOG = '\x10';
